In [ ]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [74]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [5]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [6]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [64]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   
                                   index = False,
                                   header = False)

In [65]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(
    chunk_size=2011,  # Must be > 0
    chunk_overlap=0, 
    separator="\n"
)
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 2012, which is longer than the specified 2011
Created a chunk of size 2834, which is longer than the specified 2011
Created a chunk of size 2510, which is longer than the specified 2011
Created a chunk of size 2285, which is longer than the specified 2011
Created a chunk of size 2616, which is longer than the specified 2011
Created a chunk of size 2032, which is longer than the specified 2011
Created a chunk of size 2762, which is longer than the specified 2011
Created a chunk of size 2141, which is longer than the specified 2011
Created a chunk of size 2209, which is longer than the specified 2011
Created a chunk of size 2877, which is longer than the specified 2011
Created a chunk of size 2400, which is longer than the specified 2011
Created a chunk of size 2122, which is longer than the specified 2011
Created a chunk of size 2181, which is longer than the specified 2011
Created a chunk of size 2171, which is longer than the specified 2011
Created a chunk of size 2723, which is longer than the specified 2011
Created a chunk of size 2456, which is longer than the specified 2011
Created a chunk of size 2450, which is longer than the specified 2011
Created a chunk of size 3170, which is longer than the specified 2011
Created a chunk of size 2034, which is longer than the specified 2011
Created a chunk of size 2033, which is longer than the specified 2011
Created a chunk of size 2942, which is longer than the specified 2011
Created a chunk of size 2148, which is longer than the specified 2011
Created a chunk of size 2490, which is longer than the specified 2011
Created a chunk of size 3784, which is longer than the specified 2011
Created a chunk of size 2702, which is longer than the specified 2011
Created a chunk of size 5836, which is longer than the specified 2011
Created a chunk of size 2075, which is longer than the specified 2011
Created a chunk of size 2084, which is longer than the specified 2011
Created a chunk of size 2299, which is longer than the specified 2011
Created a chunk of size 2073, which is longer than the specified 2011
Created a chunk of size 2023, which is longer than the specified 2011
Created a chunk of size 2024, which is longer than the specified 2011
Created a chunk of size 2372, which is longer than the specified 2011
Created a chunk of size 2351, which is longer than the specified 2011
Created a chunk of size 2350, which is longer than the specified 2011
Created a chunk of size 2334, which is longer than the specified 2011
Created a chunk of size 2946, which is longer than the specified 2011
Created a chunk of size 3243, which is longer than the specified 2011
Created a chunk of size 2780, which is longer than the specified 2011
Created a chunk of size 2085, which is longer than the specified 2011
Created a chunk of size 2018, which is longer than the specified 2011
Created a chunk of size 2713, which is longer than the specified 2011
Created a chunk of size 2278, which is longer than the specified 2011
Created a chunk of size 2053, which is longer than the specified 2011
Created a chunk of size 2016, which is longer than the specified 2011
Created a chunk of size 2069, which is longer than the specified 2011
Created a chunk of size 2857, which is longer than the specified 2011
Created a chunk of size 2869, which is longer than the specified 2011
Created a chunk of size 2347, which is longer than the specified 2011
Created a chunk of size 2453, which is longer than the specified 2011
Created a chunk of size 2149, which is longer than the specified 2011
Created a chunk of size 2742, which is longer than the specified 2011
Created a chunk of size 3938, which is longer than the specified 2011

In [66]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [75]:
db_books = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings())

In [76]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='4f5557fa-87d3-49c6-8f3d-e2dac92199bc', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='680ab662-7ca3-4aa4-9677-a6c89563ef53', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."\n"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."\n"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."\n"9780786808717 A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!"'),
 Document(id='47f1131d-eb6f-448f-b170-bcebdf260b29', metadata={'source': 'tagged_description.txt'}, page_content='"9780671631987 With more than half a million copies in print, Teach Your Child to Read in 100 Easy Lessons is the definitive guide to giving your child the reading skills needed now for a better chance at tomorrow, while bringing you and your child closer together. Is your child halfway through first grade and still unable to read? Is your preschooler bored with coloring and ready for reading? Do you want to help your child read, but are afraid you’ll do something wrong? Teach Your Child to Read in 100 Easy Lessons is a complete, step-by-step program that shows patents simply and clearly how to teach their children to read. Twenty minutes a day is all you need, and within 100 teaching days your child will be reading on a solid second-grade reading level. It’s a sensible, easy-to-follow, and enjoyable way to help your child gain the essential skills of reading. Everything you need is here—no paste, no scissors, no flash cards, no complicated directions—just you and your child learning together. One hundred lessons, fully illustrated and color-coded for clarity, give your child the basic and more advanced skills needed to become a good reader."\n"9780671646196 Nancy Harding uses her storytelling gifts to depict a young woman who would defy every tradition of her male-dominated society--and triumph! Set against the ancient world of the Scythian tribes of 513 B.C., Wind Child is a passionate, exhilarating, unforgettable tale."\n"9780671662349 The reminiscences of Miep Gies, the woman who hid the Frank family in Amsterdam during the Second World War, presents a vivid story of life under Nazi occupation."\n"9780671685638 Questions arise concerning the connections between a strangely detached young girl\'s captivity in a seedy Florida motel, a death that occurs at a party for a visiting actress, and a young California instructor\'s obsession with one of his students"'),
 Document(id='df1f8d96-c6d6-4da7-a517-fa2cfc7fa6e2', metadata={'source': 'tagged_description.txt'}, page_content='9780762427321 Hawking\'s revolutionary look at the scientific discoveries that changed people\'s perceptions of the world now comes complete with color photographs and illustrations depicting theoretical models of the planets and their orbits.\n"9780763619312 When a third grade classmate gets her picture in the paper for winning a spelling bee, Judy is determined to find a way to become famous herself."\n"9780763620875 When Judy Moody gets serious about protecting the environment, her little brother Stink thinks she is overdoing it, but she manages to inspire her third grade class to undertake an award-winning, environment-saving project. Reprint."\n"9780763621643 As a page in his uncle\'s castle in thirteenth-century England, eleven-year-old Tobias records in his journal his experiences learning how to hunt, play games of skill, and behave in noble society."\n"9780763625894 Edward Tulane, a cold-hearted and proud toy rabbit, loves only himself until he is separated from the little girl who adores him and travels across the country, acquiring new owners and listening to their hopes, dreams, and histories. Jr Lib Guild. Teacher\'s Guide available. 300,000 first printing."\n"9780763626150 Judy is excited about becoming a doctor, especially when Class 3T starts a new unit on the human body, but she learns more about being a patient when she catches tonsillitis from her little brother, Stink. Reprint. 75,000 first printing."\n"9780763628000 After learning about the American Revolution on a family trip to Boston, Massachusetts, Judy Moody makes her own Declaration of Independence and tries to prove that she is responsible enough to have more freedoms, such as a higher allowance and her own bathroom. Reprint."\n"9780763628109 When twelve-year-old Daniel Cook and his sister, Beatrice, spend the summer at a special school run by their parents\' eccentric former tutor, they are introduced to the secret study of dragonology and find themselves caught up in an evil plot."'),
 Document(id='2cf1cddf-b094-479d-9688-f406c0ddcf32', metadata={'source': 'tagged_description.txt'}, page_content='"9780786811052 Thirteen-year-old Ricky, the Mexican American son of a former Drug Enforcement Agency man, tries to avenge his mother\'s murder by crossing over into Mexico to steal a high-tech radar plane from drug smugglers."\n"9780786812912 In her first illustrated book for children, the Pulitzer Prize–winning author Toni Morrison introduces three feisty children who show grown-ups what it really means to be a kid."\n"9780786813858 Chanel\'s passion for fashion gets the best of her when she goes on a clothes shopping spree with her mother\'s credit card, until the credit trail catches up with her and she is forced to pay up. Original. 50,000 first printing."\n"9780786815937 Seventeen-year-old Vince Luca\'s life is constantly complicated by the fact that he is the son of a powerful Mafia boss, a relationship that threatens to destroy his romance with the daughter of an FBI agent. Reprint."\n"9780786816156 A BookSense 76 pick, and best-seller from coast to coast-Summerland is part fantasy, part adventure, part baseball, but most of all it\'s the story of a young boy, Ethan Feld-a lousy, but lovable little-leaguer who finds himself playing in the most important baseball game ever. Not only the game, but the fate of the world rests on his shoulders."\n"9780786818723 Violet, a very curious young mouse, invites babies and toddlers into her home to explore, room by room, her favorite things. Delightfully written rhythmic verse and engaging illustrations lead children to discover the feel of objects that surround them in their everyday world. From touching Violet\'s fluffy poodle to joining her as she puts sticky toothpaste on her brush, children will want to visit Violet\'s House time and time again."\n"9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."'),
 Document(id='376f00a7-7d1b-44dc-9f46-6bfbf5b98633', metadata={'source': 'tagged_description.txt'}, page_content='9780029221303 A blending of scholarly research and interviews with many of the figures who launched the civil rights movement in the 1960s and 1970s records the events of the movement\'s tumultuous first decade\n9780030547744 A young boy living in the Ozarks achieves his heart\'s desire when he becomes the owner of two redbone hounds and teaches them to be champion hunters.\n"9780060000141 There\'s trouble at Gray House, the girlhood home that Poppy left long ago. Poppy\'s family has called her back to save them all—mother, father, sisters and brothers, and dozens and dozens of deer mouse cousins. Poppy invites her rebellious son, Junior, to join her on the long trip across Dimwood Forest, hoping the journey will bring them closer together. But with Junior\'s skunk pal, Mephitis, and Ereth, the cantankerous porcupine, in tow—sugared slug soup!—Poppy and Junior may be in for unexpected adventure."\n"9780060001537 This is the diary ... of a spider. But don\'t be worried – he\'s more scared of you and your gigantic shoe! Actually, he\'s a lot like you. He goes to gym class and has Grandparents\' Day at school. But he also spins sticky webs, scales walls, and takes wind–catching lessons. Lucky for him, his best friend is a fly! Doreen Cronin and Harry Bliss, the team behind the #1 bestselling Diary Of A Worm, spin a hilarious tale about the upside–down web world of an eight–legged charmer and his unlikely friend, Fly."\n9780060004507 An adaptation of the original story follows the activities of seven children in nineteenth-century New England as they prepare for the Thanksgiving holiday while Mother is away caring for Grandmother.\n"9780060005696 The author of The Battle for Human Nature explains why too much choice has led to the ever increasing complexity of everyday decisions, why too much of a good thing has become detrimental to human psychological and emotional well-being, and how to focus our lives on making the right choices. Reprint. 35,000 first printing."'),
 Document(id='df2c539d-a1f1-409f-97b4-f2ad6864724b', metadata={'source': 'tagged_description.txt'}, page_content='"9780876851388 Mockingbird Wish Me Luck captures glimpses of Charles Bukowski\'s view on life through his poignant poetry: the pain, the hate, the love, and the beauty. He writes of lechery and pain while finding still being able to find its beauty."\n"9780876856833 Charles Bukowski examines cats and his childhood in You Get So Alone at Times, a book of poetry that reveals his tender side. He delves into his youth to analyze its repercussions."\n"9780877887263 We are all strangers in a strange land, longing for home, but not quite knowing what or where home is. We glimpse it sometimes in our dreams, or as we turn a corner, and suddenly there is a strange, sweet familiarity that vanishes almost as soon as it comes… –Madeleine L’Engle, from The Rock That Is Higher Story captures our hearts and feeds our imaginations. It reminds us who we are and where we came from. Story gives meaning and direction to our lives as we learn to see it as an affirmation of God’s love and truth–an acknowledgment of our longing for a rock in the midst of life’s wilderness. Drawing upon her own experiences, well-known tales in literature, and selected narratives from Scripture, Madeleine L’Engle gently leads the way into the glorious world of story in The Rock That Is Higher. Here she acknowledges universal human longings and considers how literature, Scripture, personal stories, and life experiences all point us toward our true home."\n"9780878937202 Essentials of Conservation Biology (Fourth Edition) combines theory and basic research to explain the connections between conservation biology and environmental economics, education, ethics, law and the social sciences. It is beautifully illustrated and is written in clear, non-technical language. The book\'s broad, up-to-date coverage and its extensive bibliography with over 1,000 references also make it invaluable to graduate students and researchers. This new edition now comes with a Glossary."'),
 Document(id='d92cfc5a-fbd8-4f1d-b16f-cac6be66bd7d', metadata={'source': 'tagged_description.txt'}, page_content='"9780152045739 A little lighthouse on the Hudson River regains its pride when it finds out that it is still useful and has an important job to do, in a tale first published in 1942. Reprint. 30,000 first printing"\n"9780152049676 A child describes pleasant ways to stay warm during the winter, from sipping hot chocolate and eating grilled cheese sandwiches to wearing woolly sweaters and sitting near a glowing fireplace."\n"9780152050863 In 1520, thirteen-year-old Anne Boleyn, jealous of her older sister\'s beauty and position at court, declares that she will one day be queen of England, and that her sister will kneel at her feet."\n"9780152051242 When a young man in the Uplands blinds himself rather than use his gift of ""unmaking""--a violent talent shared by members of his family--he upsets the precarious balance of power among rival, feuding families, each of which has a strange and deadly talent of its own. Reprint."\n"9780152052607 In winning a medal she is no longer there to receive, a tight-lipped little Polish girl teaches her classmates a lesson. Includes a note from the author\'s daughter, Helena Estes."\n"9780152054472 In 1501, fifteen-year-old Catharine of Aragon arrives in England and marries Arthur, the eldest son of King Henry VII, but when Arthur unexpectedly dies, her future becomes the subject of a bitter dispute between England and Spain."\n"9780152057640 Raised by a great-grandmother and a bunch of beauty shop buddies, fourteen-year-old Abbey resolves to overcome her unhappy childhood and disillusionment with the mother who deserted her."\n9780152758516 Three short tall tales : The sleeping giant -- The lost shadow -- A nice room for giraffes - written and illustrated by Eleanor Estes.\n"9780156001267 A new translation of the most famous work of a witty, irreverent Roman poet captures the mischievous spirit of this man of letters who wrote candid poems about love and suffered a death in exile."'),
 Document(id='981250ae-698b-438e-889b-e5552fb7c35b', metadata={'source': 'tagged_description.txt'}, page_content='"9781586857721 Provides a comprehensive guide to adopting greener buying habits and identifying earth-friendly products, shopping for green products online, participating in online activism, and learning tips for cultivating a sustainable environment, such as collecting rainwater from your roof to use in the garden, submerging a plastic bottle in your toilet tank to save one quart of water per flush, and more. Original."\n"9781587150791 Lord Dunsany was one of the most influential writers of fantasy fiction in 20th century. ""Fifty-One Tales"" (originally published in 1915 and sometimes reprinted under the title ""The Food of Death"") is an ideal introduction to Dunsany."'),
 Document(id='7177930c-b31c-42ed-ae24-fe238ee8442f', metadata={'source': 'tagged_description.txt'}, page_content='"9780747548317 In the aquarium at the London Zoo, three sea turtles swim endlessly in \'their little bedsitter of ocean\'. Two lonely people, William G and Neaera H, become obsessed with the turtles\' captivity, and resolve to rescue them and release them in to the sea. William\'s and Neaera\'s diaries tell the story of how they achieve the turtles\' freedom, and in the process re-define their own lives."\n"9780747553663 Since Christopher Ransom has been living in Kyoto, the ancient capital of Japan, he has devoted himself to the study of karate. He doesn\'t just want to be good, he wants to be transformed. Two years after a lapse in his scruples drew him into crisis on the Khyber Pass, it is through karate that Ransom has regained some control, beginning to subsume his disillusionment and assuage his guilt. But soon he finds himself threatened by everything he thought he had left behind -- a sequence of bizarre events whose consequences he cannot escape."\n"9780747553861 Pastoralia was published to huge literary acclaim, establishing George Saunders, one of the New Yorker\'s \'twenty writers for the 21st century\', as one of the most hypnotic and original voices of contemporary fiction."\n"9780747563006 Pollan tells the story of four domesticated species - the apple, the tulip, marijuana and the potato, and describes how each has thrived by satisfying humankind\'s most basic desires."\n"9780747564171 This is the story of the Tuck family, who are doomed to - or blessed with - eternal life after drinking from a magic spring."')]

In [81]:
books[books["isbn13"] == int(docs[2].page_content.split()[0].strip().strip('"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,2083.0,Teach Your Child to Read in 100 Easy Lessons,9780671631987 With more than half a million co...

In [82]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [84]:
retrieve_semantic_recommendations("human relationships")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
84,9780029221303,0029221307,The Origins of the Civil Rights Movement,Aldon D. Morris,History,http://books.google.com/books/content?id=7vyHY...,A blending of scholarly research and interview...,1986.0,4.04,368.0,145.0,The Origins of the Civil Rights Movement,9780029221303 A blending of scholarly research...
101,9780060175641,0060175648,Identity,Milan Kundera,Fiction,http://books.google.com/books/content?id=D30Ex...,Milan Kundera's Identity translated from the F...,1998.0,3.68,176.0,260.0,Identity: A Novel,9780060175641 Milan Kundera's Identity transla...
156,9780060574215,0060574216,"Men Are from Mars, Women Are from Venus",John Gray,Family & Relationships,http://books.google.com/books/content?id=MUw_d...,Rediscover the most famous relationship book e...,2004.0,3.54,368.0,126108.0,"Men Are from Mars, Women Are from Venus: The C...",9780060574215 Rediscover the most famous relat...
189,9780060652890,0060652896,The Screwtape Letters,C. S. Lewis,Religion,http://books.google.com/books/content?id=v1kn7...,In this humorous and perceptive exchange betwe...,2001.0,4.22,224.0,116735.0,The Screwtape Letters,9780060652890 In this humorous and perceptive ...
284,9780060916091,0060916095,Think on These Things,Jiddu Krishnamurti,Religion,http://books.google.com/books/content?id=Qzzbm...,‘The material contained in this volume was ori...,1989.0,4.40,258.0,2288.0,Think on These Things,9780060916091 ‘The material contained in this ...
292,9780060925758,0060925752,Soul Mates,Thomas Moore,Psychology,http://books.google.com/books/content?id=7syEl...,This companion volume to Care of the Soul offe...,1994.0,4.00,288.0,4122.0,Soul Mates,9780060925758 This companion volume to Care of...
301,9780060930318,0060930314,Identity,Milan Kundera,Fiction,http://books.google.com/books/content?id=mXPU2...,There are situations in which we fail for a mo...,1999.0,3.68,168.0,13065.0,Identity: A Novel,9780060930318 There are situations in which we...
365,9780061122095,0061122092,By the River Piedra I Sat Down and Wept,Paulo Coelho,Fiction,http://books.google.com/books/content?id=9AHal...,"From Paulo Coelho, author of the international...",2006.0,3.57,208.0,68403.0,By the River Piedra I Sat Down and Wept: A Nov...,"9780061122095 From Paulo Coelho, author of the..."
370,9780061129735,0061129739,The Art of Loving,Erich Fromm,Self-Help,http://books.google.com/books/content?id=TRMED...,The fiftieth Anniversary Edition of the ground...,2006.0,4.03,192.0,35605.0,The Art of Loving,9780061129735 The fiftieth Anniversary Edition...
388,9780061196676,0061196673,Smithsonian Intimate Guide to Human Origins,Carl Zimmer,Social Science,http://books.google.com/books/content?id=xufuS...,From the savannas of Africa to modern-day labs...,2007.0,4.00,176.0,167.0,Smithsonian Intimate Guide to Human Origins,9780061196676 From the savannas of Africa to m...
443,9780070488205,0070488207,Virgin,James Patterson,Fiction,NaN,The Blessed Virgin's deliverance of a prophecy...,1980.0,3.86,210.0,300.0,Virgin,9780070488205 The Blessed Virgin's deliverance...
502,9780099458265,0099458268,Human Traces,Sebastian Faulks,Europe,http://books.google.com/books/content?id=KTKZi...,As young boys both Jacques RebiSre and Thomas ...,2006.0,3.63,793.0,3388.0,Human Traces,9780099458265 As young boys both Jacques RebiS...
562,9780140128468,0140128468,Love's Executioner,Irvin D. Yalom,Existential psychotherapy,http://books.google.com/books/content?id=ZBptQ...,Contains eight case-studies of people the auth...,1991.0,4.20,270.0,216.0,Love's Executioner: And Other Tales of Psychot...,9780140128468 Contains eight case-studies of p...
700,9780140449129,0140449124,Madame Bovary,Gustave Flaubert;Geoffrey Wall,Fiction,http://books.google.com/books/content?id=2XIoO...,"An unhappily married woman, Emma Bovary's unfu...",2003.0,3.66,327.0,3484.0,Madame Bovary,"9780140449129 An unhappily married woman, Emma..."
946,9780192802644,019280264X,Mansfield Park,Jane Austen,Literary Criticism,http://books.google.com/books/content?id=jl6iD...,"'""Me!"" cried Fanny...""Indeed you must excuse m...",2003.0,3.85,418.0,1471.0,Mansfield Park,"9780192802644 '""Me!"" cried Fanny...""Indeed you..."
1108,9780285647473,0285647474,Zen Buddhism & Psychoanalysis,Daisetz Teitaro Suzuki;Erich Fromm;Richard De ...,Psychoanalysis and religion,http://books.google.com/books/content?id=wMEAJ...,The key book in our quest for understanding of...,1974.0,3.94,188.0,517.0,Zen Buddhism & Psychoanalysis,9780285647473 The key book in our quest for un...
1114,9780299125400,0299125408,Mark Twain's Own Autobiography,Mark Twain,"Authors, American",http://books.google.com/books/content?id=ZehUN...,Fifteen studies are grouped into three closely...,1990.0,3.83,301.0,9.0,Mark Twain's Own Autobiography: The Chapters f...,9780299125400 Fifteen studies are grouped into...
1255,9780312423131,0312423136,Galatea 2.2,Richard Powers,Fiction,http://books.google.com/books/content?id=ttcEu...,"The protagonist, a Humanist-in-Residence at th...",2004.0,3.72,329.0,2063.0,Galatea 2.2: A Novel,"9780312423131 The protagonist, a Humanist-in-R..."
1387,9780330340328,0330340328,The Reality Dysfunction,Peter F. Hamilton,English fiction,http://books.google.com/books/content?id=uOqwr...,In AD 2600 the human race is finally beginning...,1997.0,4.14,1223.0,26269.0,The Reality Dysfunction,9780330340328 In AD 2600 the human race is fin...
1434,9780340831205,0340831200,The Art of Happiness at Work,Dalai Lama XIV Bstan-ʼdzin-rgya-mtsho;Howard C...,Buddhism,http://books.google.com/books/content?id=gQqON...,Following the massive success of THE ART OF HA...,2003.0,4.16,224.0,1583.0,The Art of Happiness at Work,9780340831205 Following the massive success of...
1928,9780393327656,0393327655,"The End of Faith: Religion, Terror, and the Fu...",Sam Harris,Philosophy,http://books.google.com/books/content?id=V1NXG...,An analysis of the disparity between faith and...,2005.0,3.94,348.0,28188.0,"The End of Faith: Religion, Terror, and the Fu...",9780393327656 An analysis of the disparity bet...
1954,9780394536491,0394536495,The Castle in the Forest,Norman Mailer,Fiction,http://books.google.com/books/content?id=gsFmA...,A mysterious SS man offers an insightful glimp...,2007.0,3.13,477.0,2258.0,The Castle in the Forest: A Novel,9780394536491 A mysterious SS man offers an in...
2459,9780465024964,0465024963,The Classical World,Robin Lane Fox,History,http://books.google.com/books/content?id=Srhcj...,"Armies and empires, statesmen and tyrants--the...",2005.0,3.92,672.0,1222.0,The Classical World: An Epic History from Home...,"9780465024964 Armies and empires, statesmen an..."
2462,9780465056743,0465056741,Philosophy In The Flesh,George Lakoff,Philosophy,http://books.google.com/books/content?id=csASt...,What are human beings like? How is knowledge p...,1999.0,4.07,640.0,1100.0,Philosophy In The Flesh,9780465056743 What are human beings like? How ...
2590,9780520244955,0520244958,Giovanni and Lusanna,Gene Brucker,History,http://books.google.com/books/content?id=47EwD...,"""Set against the grindstone of social class, t...",2005.0,3.56,160.0,250.0,Giovanni and Lusanna: Love and Marriage in Ren...,"9780520244955 ""Set against the grindstone of s..."
2859,9780590103879,0590103873,Expository Writing,Tara McCarthy,Juvenile Nonfiction,http://books.google.com/books/content?id=9HKHF...,A Down-to-Earth Approach James Henslin shares ...,1998.0,4.33,88.0,3.0,Expository Writing,9780590103879 A Down-to-Earth Approach James H...
2922,9780618471164,0618471162,"Since 1500, Chapters 15-30",Richard W. Bulliet,Science,http://books.google.com/books/content?id=DS0C7...,The Earth and Its Peoples Brief Edition is a c...,2005.0,4.00,34.0,8.0,"Since 1500, Chapters 15-30: The Earth and Its ...",9780618471164 The Earth and Its Peoples Brief ...
2954,9780670034666,0670034665,Self-made Man,Norah Vincent,Social Science,http://books.google.com/books/content?id=PGiBQ...,A Los Angeles Times columnist recounts her eig...,2006.0,3.32,290.0,4053.0,Self-made Man: One Woman's Journey Into Manhoo...,9780670034666 A Los Angeles Times columnist re...
2995,9780671519988,0671519980,The Leader In You,Dale Carnegie,Self-Help,http://books.google.com/books/content?id=kvE_l...,"For nearly a century, the words and works of D...",1995.0,4.09,256.0,3550.0,The Leader In You: The Leader In You,"9780671519988 For nearly a century, the words ..."
3038,9780674644847,0674644840,Origins of the Modern Mind,Merlin Donald,Medical,http://books.google.com/books/content?id=4Sk4v...,This bold and brilliant book asks the ultimate...,1991.0,4.17,424.0,88.0,Origins of the Modern Mind: Three Stages in th...,9780674644847 This bold and brilliant book ask...
3103,9780679759256,0679759255,When She was Good,Philip Roth,Fiction,http://books.google.com/books/content?id=Qsw1H...,"In this funny and chilling novel, the setting ...",1995.0,3.53,320.0,1639.0,When She was Good,9780679759256 In this funny and chilling novel...
3176,9780687002825,0687002826,Exclusion and Embrace,Miroslav Volf,Religion,http://books.google.com/books/content?id=Cqto7...,Life at the end of the twentieth century prese...,1996.0,4.27,306.0,1895.0,Exclusion and Embrace: A Theological Explorati...,9780687002825 Life at the end of the twentieth...
3216,9780689863110,068986311X,The Eagle,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=cxC9X...,Two mice that live in a lighthouse along with ...,2005.0,4.08,64.0,155.0,The Eagle,9780689863110 Two mice that live in a lighthou...
3296,9780743202411,0743202414,A Primate's Memoir,Robert M. Sapolsky,Nature,http://books.google.com/books/content?id=90Iil...,In the tradition of Jane Goodall and Dian Foss...,2002.0,4.35,304.0,4769.0,A Primate's Memoir: A Neuroscientist's Unconve...,9780743202411 In the tradition of Jane Goodall...
3343,9780743269261,0743269268,The Virgin's Lover,Philippa Gregory,Fiction,http://books.google.com/books/content?id=tc-nD...,From #1 New York Times bestselling author and ...,2005.0,3.70,441.0,42685.0,The Virgin's Lover,9780743269261 From #1 New York Times bestselli...
3347,9780743270793,0743270797,Untouchables,Narendra Jadhav,Biography & Autobiography,http://books.google.com/books/content?id=k9hfQ...,Every sixth human being in the world today is ...,2005.0,3.82,320.0,299.0,Untouchables: My Family's Triumphant Journey O...,9780743270793 Every sixth human being in the w...
3353,9780743272773,0743272773,How to Win Friends and Influence People for Te...,Donna Dale Carnegie,Self-Help,http://books.google.com/books/content?id=eIc2l...,"Donna Dale Carnegie, daughter of the late moti...",2005.0,3.90,208.0,426.0,How to Win Friends and Influence People for Te...,"9780743272773 Donna Dale Carnegie, daughter of..."
3403,9780743468596,0743468597,First Things First,Stephen R. Covey,Conduct of life,http://books.google.com/books/content?id=KRZEP...,In the spirit of THE 7 HABITS OF HIGHLY EFFECT...,2002.0,4.09,360.0,23.0,"First Things First: To Live, to Love, to Learn...",9780743468596 In the spirit of THE 7 HABITS OF...
3428,9780743495929,0743495926,Getting the Love You Want,Harville Hendrix,Love,http://books.google.com/books/content?id=Vc56P...,"Originally published in 1988, GETTING THE LOVE...",2005.0,4.07,336.0,5513.0,Getting the Love You Want: A Guide for Couples,"9780743495929 Originally published in 1988, GE..."
3489,9780750937252,0750937254,Ulysses Found,Ernle Bradford,History,http://books.google.com/books/content?id=QBdGP...,Having settled in Malta after the end of World...,2005.0,4.04,238.0,34.0,Ulysses Found,9780750937252 Having settled in Malta after th...
3719,9780785260059,0785260056,The Power of One,John C. Maxwell;Thomas G. Addington,Business & Economics,http://books.google.com/books/content?id=L_FGs...,In this 30-day companion workbook to There's N...,2004.0,4.28,256.0,16.0,"The Power of One: One Person, One Rule, One Month",9780785260059 In this 30-day companion workboo...
3835,9780802713520,0802713521,E=mc2,David Bodanis,Science,http://books.google.com/books/content?id=Y5FwQ...,Generations have grown up knowing that the equ...,2000.0,4.09,352.0,157.0,E=mc2: A Biography of the World's Most Famous ...,9780802713520 Generations have grown up knowin...
4069,9780822560562,0822560569,Barack Obama,Marlene Targ Brill,Juvenile Nonfiction,http://books.google.com/books/content?id=FIhyP...,Chronicles the life and career of the communit...,2006.0,3.96,48.0,19.0,Barack Obama: Working to Make a Difference,9780822560562 Chronicles the life and career o...
4135,9780849918728,0849918723,Lead Like Jesus,Ken Blanchard;Phil Hodges,Religion,http://books.google.com/books/content?id=nEAqu...,"The author of One Minute Manager, one of the w...",2007.0,4.03,239.0,759.0,Lead Like Jesus,9780849918728 The author of One Minute Manager...
4242,9780918273826,091827382X,Through the Arc of the Rain Forest,Karen Tei Yamashita,Fiction,http://books.google.com/books/content?id=Pf92t...,"A wealthy Japanese man, a Brazilian healer, a ...",1990.0,3.91,212.0,119.0,Through the Arc of the Rain Forest: A Novel,"9780918273826 A wealthy Japanese man, a Brazil..."
4278,9780966410075,0966410076,You are Being Lied to,Russell Kick,Language Arts & Disciplines,http://books.google.com/books/content?id=KALsz...,This book acts as a battering ram against the ...,2001.0,3.87,399.0,995.0,You are Being Lied to: The Disinformation Guid...,9780966410075 This book acts as a battering ra...
4710,9781575667645,1575667649,Bound in Blood,David Thomas Lord,Fiction,http://books.google.com/books/content?id=7PYZZ...,"As a vampire, art critic Jean-Luc ""Jack"" Courb...",2001.0,3.32,352.0,69.0,Bound in Blood,"9781575667645 As a vampire, art critic Jean-Lu..."
4774,9781583224717,1583224718,Lithium for Medea,Kate Braverman,Fiction,http://books.google.com/books/content?id=aKsC0...,Probes the strained relationships between a wo...,2002.0,3.94,362.0,331.0,Lithium for Medea: A Novel,9781583224717 Probes the strained relationship...
4842,9781590302088,1590302087,Making a Change for Good,Cheri Huber,Philosophy,http://books.google.com/books/content?id=rnt1n...,"In her new book, Huber takes on the topic of c...",2007.0,3.92,128.0,291.0,Making a Change for Good: A Guide to Compassio...,"9781590302088 In her new book, Huber takes on ..."
4910,9781594731402,1594731403,How to be a Perfect Stranger,Stuart M. Matlins;Arthur J. Magida,Reference,http://books.google.com/books/content?id=3vDI7...,A guide to the rituals and celebrations of the...,2006.0,3.96,403.0,114.0,How to be a Perfect Stranger: The Essential Re...,9781594731402 A guide to the rituals and celeb...